# Generated by Django 5.0 on 2023-12-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kingdom_name", models.CharField(max_length=250)),
                ("species", models.CharField(max_length=250)),
                ("number_of_species", models.IntegerField(default=1, null=True)),
                ("animal_class", models.CharField(max_length=250)),
                ("order", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english_name", models.CharField(max_length=250)),
                ("scientific_name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("areas_in_Uganda", models.CharField(max_length=250)),
                ("known_values", models.CharField(max_length=250)),
                ("value_details", models.CharField(max_length=250)),
                ("unique_habitat", models.CharField(max_length=250)),
                ("threats", models.TextField()),
                ("notes", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="animal_images"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="animal_videos"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="animal_audios"),
                ),
                ("citation", models.TextField()),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "animal_classifications",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="animals.animalclassification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalLocalName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_name", models.CharField(max_length=250)),
                ("language", models.CharField(max_length=250)),
                (
                    "animal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animals.animal",
                    ),
                ),
            ],
        ),
    ]
