# Generated by Django 5.0 on 2023-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicinalplantname",
            name="is_english",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plantname",
            name="is_english",
            field=models.BooleanField(default=False),
        ),
    ]
