# Generated by Django 5.0 on 2023-12-06 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0002_medicinalplantname_is_english_plantname_is_english"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicinalplantname",
            name="is_english",
        ),
        migrations.RemoveField(
            model_name="plantname",
            name="is_english",
        ),
    ]
