# Generated by Django 5.0 on 2023-12-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0003_remove_medicinalplantname_is_english_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="medicinalplantname",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="plantname",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
