# Generated by Django 5.0 on 2023-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0004_alter_language_name_alter_medicinalplantname_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant",
            old_name="cultural_value",
            new_name="known_values",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="economical_value",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="other_value",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="social_value",
        ),
        migrations.AddField(
            model_name="medicinalplant",
            name="cultural_value",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
