# Generated by Django 5.0 on 2023-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0005_rename_cultural_value_plant_known_values_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant",
            old_name="habitat",
            new_name="climate_Impact",
        ),
        migrations.AddField(
            model_name="plant",
            name="threats",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="unique_habitat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
