name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show Current Directory
        run: |
          echo "Current Directory: $(pwd)"

      - name: List Files
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set DATABASE_URL for Django Tests
        run: echo "DATABASE_URL=${DATABASE_URL}" >> $GITHUB_ENV

      - name: Grant Database Permissions
        run: |
          # Assuming your DATABASE_URL is of the form: postgresql://username:password@host:port/database
          DB_USER=$(echo $DATABASE_URL | sed -n 's/.*\/\/\([^:]*\):.*/\1/p')
          psql -U $DB_USER -c "ALTER USER $DB_USER CREATEDB;"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run Tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Set DATABASE_URL for Deployment
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Echo Hello World
        run: echo "Hello World"
